### ISSUE TITLE
Inconsistent precision-recall curve

### ISSUE THREAD

**Issue by albertus-andito** [delftdata/SiMa#2]
Hi,

Thank you for open sourcing your code.

I was just running the notebook: [matching_data_silos.ipynb](https://github.com/delftdata/SiMa/blob/master/notebooks/matching_data_silos.ipynb).

However, I don't think I managed to reproduce the same precision-recall curve for SiMa as shown on Figure 6b on the paper. The best F1 score that I got from this first run is 0.794 for the LA dataset. I used the pre-computed profiles and configurations.

I also noticed that when I re-ran the whole thing again, I got a slightly different precision-recall curve and F1 scores. Is there always a randomness factor in this? Can it be fixed with something like seed?

Many thanks.

**Comment by chrisk21** [comment]
Hi Albertus,

Thank you for reaching out. Indeed, there are two aspects of the method where randomness plays a role in the final results: i) picking the negative examples to use for training and ii) initializing the weight matrices during the training of the GNN. To make sure you get same results for each run you need to use a random seed. 

In specific, when using the provided [notebook](https://github.com/delftdata/SiMa/blob/master/notebooks/matching_data_silos.ipynb) you will need to make the following alterations:

1) Import random in the first cell, `import random`
2) Set a specific seed in the range `(0, 2*32 -1)`
3) In the cell where negative random sampling takes place (execution step 8), start with `random.seed(seed)`
4) In the cell where we train the GNN model (execution step 9), start with `torch.manual_seed(seed)`

Following the above steps will ensure that you get the same results across different runs. The reported results in the paper  represent the best run from the ones we proceeded with.

Should you have more questions, don't hesitate to contact me.

**Comment by albertus-andito** [comment]
Thanks for the response.

I can confirm that with the alterations, the results are now fixed across different runs.
